[package]
name = "llmpal"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"